language: java
jdk: oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
addons:
  apt:
    packages:
    - gnuplot
script:
    - mvn clean install
    - mvn -f=benchmark-launcher/pom.xml exec:java -Pperf
    - echo ================================================================================
    - cat benchmark-launcher/target/jmh-result.csv
    - echo ================================================================================
    - ./build_graph.sh
    - echo ================================================================================
    - cat target/jmh-result-benchmark-stocks.html.svg
    - echo ================================================================================
    - cat target/jmh-result-benchmark-response.xml.svg
    - echo ================================================================================
