language: java
jdk: oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
addons:
  apt:
    packages:
    - gnuplot
script:
    - mvn clean verify -Pperf
    - echo ================================================================================
    - cat target/jmh-result.csv
    - echo ================================================================================
    - gnuplot benchmark.plot
    - echo ================================================================================
    - cat target/jmh-result.svg
    - echo ================================================================================
