language: java
jdk: oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
addons:
  apt:
    packages:
    - gnuplot
script:
    - mvn clean verify -Pperf
    - echo ================================================================================
    - cat target/jmh-result.csv
    - echo ================================================================================
    - grep "html/stocks.html" target/jmh-result.csv | sed -r 's,^".+?\.([^."]+?)Benchmark[^"]*","\1",' > target/jmh-result-benchmark-html-stocks.csv
    - grep "xml/response.xml" target/jmh-result.csv | sed -r 's,^".+?\.([^."]+?)Benchmark[^"]*","\1",' > target/jmh-result-benchmark-xml-response.csv
    - gnuplot benchmark-html-stocks.plot
    - gnuplot benchmark-xml-response.plot
    - echo ================================================================================
    - cat target/jmh-result-benchmark-html-stocks.svg
    - cat target/jmh-result-benchmark-xml-response.svg
    - echo ================================================================================
