language: java
jdk: oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
addons:
  apt:
    packages:
    - gnuplot
branches:
  only:
    - develop
script:
    - mvn clean install
    - mvn -f=benchmark-launcher/pom.xml verify -Pperf
    - echo ================================================================================
    - cat benchmark-launcher/target/jmh-result.csv
    - echo ================================================================================
    - cat benchmark-launcher/target/template-engine-benchmarks.wiki/graph/jmh-result-benchmark-stocks.html.svg
    - echo ================================================================================
    - cat benchmark-launcher/target/template-engine-benchmarks.wiki/graph/jmh-result-benchmark-response.xml.svg
    - echo ================================================================================
    - bash ./build_graph.sh
    - echo ================================================================================
