language: java
jdk: oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
addons:
  apt:
    packages:
    - gnuplot
script:
    - mvn clean verify -Pperf
    - echo ================================================================================
    - cat target/jmh-result.csv
    - echo ================================================================================
    - grep "html/stocks.html" target/jmh-result.csv | sed -r 's,^".+?\.([^."]+?)Benchmark[^"]*","\1",' > target/jmh-result-benchmark-stocks.html.csv
    - grep "xml/response.xml" target/jmh-result.csv | sed -r 's,^".+?\.([^."]+?)Benchmark[^"]*","\1",' > target/jmh-result-benchmark-response.xml.csv
    - gnuplot benchmark-stocks.html.plot
    - gnuplot benchmark-response.xml.plot
    - echo ================================================================================
    - cat target/jmh-result-benchmark-stocks.html.svg
    - cat target/jmh-result-benchmark-response.xml.svg
    - echo ================================================================================
